package MultiThreading;

class BracketGenerate3{


     synchronized static public void generate(String threadCod){



            for (int x = 1; x <= 10; x++) {
                try {
                    Thread.sleep(10);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
                if (x <= 5) {
                    System.out.print("[");
                } else {
                    System.out.print("]");
                }
            }
        System.out.println("Generated By : "+threadCod);


    }
}
public class StaticSynchronized {
    public static void main(String[] args) {
      //  BracketGenerate3 bracketGenerate=new BracketGenerate3("1");
       // BracketGenerate3 bracketGenerate2=new BracketGenerate3("2");
        new Thread(new Runnable() {
            @Override
            public void run() {

                for (int i=1;i<=5;i++){
                    BracketGenerate3.generate("1");
                }

            }
        }).start();

        new Thread(new Runnable() {
            @Override
            public void run() {

                for (int i=1;i<=5;i++){
                    BracketGenerate3.generate("2");
                }

            }
        }).start();
    }
}
